version: '3'

services:
  schtroumpsify:
    image: selrahcd/schtroumpsify:${SCHTROUMPSIFY_VERSION}
    networks:
      - default
      - proxy
    restart: always

  frmg_back:
    restart: always

  frmg:
    restart: always

networks:
  proxy:
    external: true