version: '3'
services:
  schtroumpsify:
    image: selrahcd/schtroumpsify:latest
    env_file:
      .env
    depends_on:
      - frmg
    networks:
      - default

  frmg_back:
      image: selrahcd/frmg:latest
      networks:
        - default

  frmg:
      image: nginx:1.17.1-alpine
      volumes:
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
          - ./fastcgi_params:/etc/nginx/conf.d/fastcgi_params
      depends_on:
        - frmg_back
      networks:
        - default